lidi = {
'Boucník (šibalský úsměv)':'Boucník (šibalský úsměv)',
'Adámková':'Adámková',
'Honza P.':'Honza P.',
'Michal Š':'Šifi',
'Anežka J.':'Anežka',
'Petr Sevelda':'Sevi',
'prof. Vomelová':'Vomelová',
'Hlásenský':'Hlása',
'Petr S':'Sevi',
'Štěpán (u tabule)':'Štěpán (u tabule)',
'Hanáková':'Hanáková',
'Petr Zelina':'Petr Z.',
'prof.':'prof.',
'Peťka Bulantová':'Peťka',
'kdosi':'kdosi',
'ze třídy':'ze třídy',
'Lucka H.':'Lucka H.',
'Lucka B.(vyzývavě)':'Lucka B.(vyzývavě)',
'posluchačka':'posluchačka',
'Kobza':'Kobza',
'Štěpán B.':'Štěpán',
'prof. ':'prof. ',
'Boucník':'Boucník',
'Anežka':'Anežka',
'Bára V.':'Bára',
'Nějaký student':'Nějaký student',
'Zuzka K.':'Zuzka',
'Anička Nevídalová':'Anička',
'všechny holky':'všechny holky',
'Honza B.':'Brzi',
'Zvolská':'Zvolská',
'prof (zničeně)':'prof. (zničeně)',
'Řehák':'Czehi',
'Tomáš B':'Krab',
'prof (naštvaně)':'prof. (naštvaně)',
'prof ':'prof.',
'Lucka Bulantová':'Lucka B.',
'Adam Č.':'Adam',
'Štěpán':'Štěpán',
'Blanka M.':'Blanka',
'Stupka':'Stupka',
'Peťka B.':'Peťka',
'Michal Š.':'Šifi',
'Petr S.':'Sevi',
'Dandi':'Dandi',
'Lucka H':'Lucka H.',
'David Paleček':'David',
'prof. Urban':'Urban',
'prof':'prof.',
'třída':'třída',
'Zuzka Kuchařová':'Zuzka',
'Zuzka':'Zuzka',
'Řihánková':'Řihánková',
'Krab':'Krab',
'šeptem zepředu':'šeptem zepředu',
'(Po chvíli zamyšlení)':'(Po chvíli zamyšlení)',
'Chalupníková':'Chalupníková',
'Matěj Ž.':'Matěj',
'Jirka P. ':'Jirka ',
'Zuzka K':'Zuzka',
'Kubištová':'Kubištová',
'Lacinová':'Lacinová',
'Vláďa':'Vláďa',
'Blanka':'Blanka',
'sprinterky':'sprinterky',
'Štěpán Balážik ':'Štěpán',
'Tomáš K.':'Kali',
'Štěpán Balážik':'Štěpán',
'Veselá':'Veselá',
}
